### ISSUE TITLE
Fails to compile on ubuntu 16.04

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/libnitrokey#46]
Commit 82a0fc21f039971acac18df0ee57e2bb010865e1 does not compile on Ubuntu 16.04 on a raspberry pi.
Older commits compile well.

It fails with the error message

    NitrokeyManager.cc:201:27: error: cannot bind packed field ‘payload.nitrokey::proto::stick10::WriteToHOTPSlot::CommandPayload::slot_counter’ to ‘long long unsigned int&’
           strcpyT(payload.slot_counter, counter.c_str());

here is the complete output:

<pre>
# make CXX=g++
g++ -M misc.cc -o build/misc.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M device.cc -o build/device.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M NK_C_API.cc -o build/NK_C_API.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -M NitrokeyManager.cc -o build/NitrokeyManager.d -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -c log.cc -o build/log.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -c NK_C_API.cc -o build/NK_C_API.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
In file included from include/device_proto.h:12:0,
                 from include/NitrokeyManager.h:6,
                 from NK_C_API.h:6,
                 from NK_C_API.cc:2:
include/cxx_semantics.h:4:44: warning: ‘__packed__’ attribute ignored for field of type ‘nitrokey::proto::DeviceResponse<cmd_id, ResponsePayload>::<anonymous union>::<anonymous struct>’ [-Wattributes]
 #define __packed __attribute__((__packed__))
                                            ^
include/device_proto.h:108:34: note: in expansion of macro ‘__packed’
                 } storage_status __packed;
                                  ^
cc1plus: warning: unrecognized command line option ‘-Wno-gnu-variable-sized-type-not-at-end’
g++ -c device.cc -o build/device.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -c misc.cc -o build/misc.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
misc.cc: In function ‘std::__cxx11::string nitrokey::misc::hexdump(const char*, size_t, bool)’:
misc.cc:44:57: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘int’ [-Wformat=]
           snprintf(formatbuf, 128, "%04lx\t", p - pstart);
                                                         ^
misc.cc:44:57: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘int’ [-Wformat=]
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-gnu-variable-sized-type-not-at-end’
g++ -c command_id.cc -o build/command_id.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
g++ -c NitrokeyManager.cc -o build/NitrokeyManager.o -Iinclude/ -std=c++14 -fPIC -Wno-gnu-variable-sized-type-not-at-end
In file included from include/device_proto.h:12:0,
                 from include/NitrokeyManager.h:6,
                 from NitrokeyManager.cc:3:
include/cxx_semantics.h:4:44: warning: ‘__packed__’ attribute ignored for field of type ‘nitrokey::proto::DeviceResponse<cmd_id, ResponsePayload>::<anonymous union>::<anonymous struct>’ [-Wattributes]
 #define __packed __attribute__((__packed__))
                                            ^
include/device_proto.h:108:34: note: in expansion of macro ‘__packed’
                 } storage_status __packed;
                                  ^
NitrokeyManager.cc: In member function ‘bool nitrokey::NitrokeyManager::write_HOTP_slot(uint8_t, const char*, const char*, uint64_t, bool, bool, bool, const char*, const char*)’:
NitrokeyManager.cc:201:27: error: cannot bind packed field ‘payload.nitrokey::proto::stick10::WriteToHOTPSlot::CommandPayload::slot_counter’ to ‘long long unsigned int&’
           strcpyT(payload.slot_counter, counter.c_str());
                           ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-gnu-variable-sized-type-not-at-end’
Makefile:28: recipe for target 'build/NitrokeyManager.o' failed
make: *** [build/NitrokeyManager.o] Error 1
</pre>

**Comment by szszszsz** [comment]
Hi! I have not checked G++ before release, my bad. It looks like Travis may be handy here.
In case it would not work please reopen.

**Comment by cornelinux** [comment]
Thanks. Now the library compiles just fine.
